apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config # arbitrary name
data: # The actual contents - key-value pairs
  mongo-url: mongo-service # this will be the service name of mongodb (endpoint)
