apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque # means the secret contains arbirary user-defined data as key-value pairs
data:
  # encoded in base64
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29YXNZd29yZA