apiVersion: apps/v2
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels: # this helps kubernetes know what pods below to this Deployment config
      app: webapp
  template: # blueprint for pods - configuration for pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0 # simple nodejs application that starts on port 3000
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret # the config file name
              key: mongo-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret # the config file name
              key: mongo-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config # the config file name
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector: # select pods to forward the request to
    app: webapp # match deployment pod label
  ports:
    - protocol: TCP
      port: 3000 # service is listening to
      targetPort: 3000 # Pod is listening to
